version: "3"
services:
  redis:
    image: redis:7-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    command: ["sh", "-c", 'exec redis-server --requirepass "$$REDIS_PASSWORD"']
    environment:
      REDIS_PASSWORD: notasecret
